channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=24.0
- pip:
  - mlflow==2.11.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.3.0
  - pyyaml==6.0.2
  - scikit-learn==1.7.0
  - scipy==1.15.3
name: mlflow-env
