name: MLFlow CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/lung_cancer_preprocessing.csv"
  TARGET_VAR: "Lung_Cancer"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run actions/checkout@v3 
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.7

    - name: Check Env
      run: |
        echo $CSV_URL
        python --version
        pip --version

    - name: Install dependencies
      run: |
        pip install -r ./MLProject/requirements.txt

    - name: Run mlflow project
      run: |
        mlflow run MLProject --env-manager=local

    - name: Get latest MLflow run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        echo "Install dependencies dari model jika perlu"
        # Contoh jika model tersimpan di MLModel
        pip install -r MLModel/requirements.txt || echo "Tidak ada file requirements"

    - name: Upload to Google Drive
      run: |
        echo "Simulasi upload artifact ke Google Drive"
